project:
  type: website

website:
  title: "PORTFOLIO"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/justinbussey
      - icon: twitter
        href: https://twitter.com/justinbussey
      - icon: linkedin
        href: https://www.linkedin.com/in/justinbussey/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

