project:
  type: website

website:
  title: "PORTFOLIO"
  navbar: 
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Resume
        href: resume.qmd
      - icon: github
        href: https://github.com/justinbussey
      - icon: linkedin
        href: https://www.linkedin.com/in/justinbussey/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual